;;;pallet-ignore
;;;manual setting
(source "ELPA" "http://tromey.com/elpa/")
(source "melpa" "https://melpa.org/packages/")
;; (source "marmalade" "https://marmalade-repo.org/packages/")
(source gnu)
(source melpa)
;; (source marmalade)

;; for org-mode
(source org)
(depends-on "ob-swift")
(depends-on "ob-typescript")
(depends-on "org-bullets")
(depends-on "org-multiple-keymap")
(depends-on "org-plus-contrib")
(depends-on "org-trello")
(depends-on "org-seek")
;; (depends-on "org-mac-link")
(depends-on "ox-gfm")
(depends-on "ox-qmd")
(depends-on "ox-hugo")

;; auto-complete
(depends-on "auto-complete")
;; (depends-on "jedi")
(depends-on "auto-complete-clang")
(depends-on "ac-c-headers")
(depends-on "ac-etags")
(depends-on "ac-inf-ruby")
(depends-on "ac-ispell")
(depends-on "ac-math")
(depends-on "ac-slime")
(depends-on "ac-octave")
(depends-on "ac-html")
;; (depends-on "ac-html-aungular")
(depends-on "ac-js2")
(depends-on "ac-emoji")

(depends-on "ace-jump-mode")
(depends-on "anzu")
(depends-on "auctex")
(depends-on "auto-async-byte-compile")

(depends-on "outline-magic")

(depends-on "auto-dictionary")
(depends-on "all-ext")
(depends-on "autopair")
(depends-on "bind-key")
(depends-on "buffer-move")
(depends-on "cask")
(depends-on "cider")
(depends-on "cl-lib")
(depends-on "clojure-mode")
(depends-on "cmake-mode")
(depends-on "cperl-mode")
(depends-on "ctable")
(depends-on "dash")
(depends-on "dash-at-point")

(depends-on "deferred")

(depends-on "dired-k")
(depends-on "dired-filter")
(depends-on "dired-hacks-utils")
(depends-on "dired-narrow")
(depends-on "dired-subtree")
(depends-on "dired-details")
(depends-on "direx")
(depends-on "dirtree")

;; tree
(depends-on "neotree")
(depends-on "speedbar")
(depends-on "sr-speedbar")

(depends-on "docker")
(depends-on "dockerfile-mode")
(depends-on "drag-stuff")
;; (depends-on "editutil" :git "https://github.com/syohex/emacs-editutil.git")

(depends-on "evil-numbers")

(depends-on "elisp-slime-nav")
(depends-on "elscreen")
(depends-on "emmet-mode")
(depends-on "enh-ruby-mode")
(depends-on "ess")
(depends-on "ess-R-data-view")
;;(depends-on "ess-R-object-popup")
(depends-on "ess-smart-underscore")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "flycheck-pos-tip")
(depends-on "flymake-css")
(depends-on "flymake-easy")
(depends-on "fringe-helper")
(depends-on "fuzzy")
(depends-on "gh")
(depends-on "ghc")
(depends-on "ghci-completion")
(depends-on "gist")


(depends-on "go-autocomplete")
(depends-on "go-eldoc")
(depends-on "golint")
(depends-on "goto-chg")
(depends-on "guide-key")

;; helm
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-rg")
(depends-on "helm-descbinds")
(depends-on "helm-ghq")
(depends-on "helm-git-grep")
(depends-on "helm-gtags")
(depends-on "helm-hatena-bookmark")
(depends-on "helm-ls-git")
(depends-on "helm-migemo")
(depends-on "helm-open-github")
(depends-on "helm-perldoc")
(depends-on "helm-pydoc")
(depends-on "helm-swoop")
(depends-on "helm-qiita")
(depends-on "helm-google")

(depends-on "hydra")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "import-popwin")
(depends-on "inf-ruby")
(depends-on "init-loader")

;; JavaScript
(depends-on "js2-mode")
(depends-on "js2-refactor")
(depends-on "prettier-js")

;; Julia
(depends-on "julia-mode")
(depends-on "julia-repl")
(depends-on "flycheck-julia")

;; Ruby
(depends-on "rinari")
(depends-on "ruby-compilation")
(depends-on "ruby-end")
(depends-on "ruby-interpolation")
(depends-on "ruby-mode")
(depends-on "ruby-test-mode")
(depends-on "ruby-tools")
(depends-on "ruby-refactor")

;; Git
(depends-on "git-commit")
(depends-on "git-dwim")
(depends-on "git-gutter")
(depends-on "git-gutter-fringe")
(depends-on "magit")

(depends-on "logito")
(depends-on "migemo")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "open-junk-file")
(depends-on "pabbrev")
(depends-on "package")
(depends-on "pallet")
(depends-on "paredit")
(depends-on "pcache")
(depends-on "php-mode")
(depends-on "popup")
(depends-on "popwin")
(depends-on "pov-mode")
(depends-on "prodigy")
(depends-on "quickrun")
(depends-on "rainbow-mode")
(depends-on "recentf-ext")
(depends-on "review-mode")
(depends-on "robe")
(depends-on "helm-robe")
(depends-on "s")
(depends-on "session")
(depends-on "slime")
(depends-on "smartparens")
(depends-on "smartrep")
(depends-on "smex")
(depends-on "sourcemap")
(depends-on "sudo-ext")
(depends-on "thingopt")
(depends-on "undo-tree")
(depends-on "use-package")
(depends-on "visual-regexp")
(depends-on "wgrep-ag")
(depends-on "with-editor")
(depends-on "wrap-region")
(depends-on "yascroll")
(depends-on "yasnippet")
(depends-on "yasnippet-snippets")
(depends-on "zeal-at-point")
(depends-on "zencoding-mode")
(depends-on "zlc")
(depends-on "zoom-window")
(depends-on "which-key")
(depends-on "neotree")

(depends-on "fish-mode")

(depends-on "w3m")

(depends-on "keyfreq")

;; projectile
(depends-on "projectile")
(depends-on "helm-projectile")

;; searching
(depends-on "ag")
(depends-on "rg")

;; programming
(depends-on "swift-mode")
(depends-on "coffee-mode")
(depends-on "typescript-mode")
(depends-on "lua-mode")
(depends-on "go-mode")
(depends-on "haskell-mode")
(depends-on "rjsx-mode")
(depends-on "rust-mode")
(depends-on "racer")
(depends-on "flycheck-rust")
(depends-on "rust-playground")
(depends-on "ein") ; for Jupyter Notebook

;; AsciiDoc
(depends-on "asciidoc")
(depends-on "ox-asciidoc")

;; markdown
(depends-on "markdown-mode")
(depends-on "markdown-mode+")
(depends-on "markdown-preview-mode")

;; web, data
(depends-on "web-mode")
(depends-on "sass-mode")
(depends-on "scss-mode")
(depends-on "haml-mode")
(depends-on "slim-mode")
(depends-on "yaml-mode")
(depends-on "toml")
(depends-on "toml-mode")

(depends-on "tide")
(depends-on "tss")
(depends-on "sync-recentf")
(depends-on "color-moccur")
(depends-on "twittering-mode")

(depends-on "esup")
(depends-on "noflet")
(depends-on "highlight2clipboard")

;; Company
(depends-on "company")
(depends-on "company-math")
(depends-on "company-reftex")
(depends-on "company-web")

;; themes
(depends-on "anti-zenburn-theme")
(depends-on "solarized-theme")
(depends-on "moe-theme")
(depends-on "monokai-theme")
(depends-on "zenburn-theme")
(depends-on "reverse-theme")
(depends-on "waher-theme")
(depends-on "heroku-theme")
(depends-on "abyss-theme")
(depends-on "ahungry-theme")
(depends-on "blackboard-theme")

(depends-on "color-theme")
(depends-on "color-theme-sanityinc-solarized")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "color-theme-solarized")
(depends-on "anti-zenburn-theme")
(depends-on "hc-zenburn-theme")
(depends-on "apropospriate-theme")
(depends-on "rebecca-theme")
(depends-on "railscasts-theme")
(depends-on "railscasts-reloaded-theme")
(depends-on "reykjavik-theme")
(depends-on "seoul256-theme")

;; writing
(depends-on "academic-phrases")
(depends-on "sudden-death")

;; misc
(depends-on "dimmer")

;; temp


;; (depends-on "moccur-edit")
;; (depends-on "flycheck-typescript-tslint")
;; (depends-on "nzenburn-theme")
;; (depends-on "color-theme-molokai")
;; (depends-on "color-theme-cobalt")
;; (depends-on "auto-complete-etags")
;; (depends-on "ac-python")
;; (depends-on "ac-ja")
;; (depends-on "ac-nrepl")
;; (depends-on "color-theme-github")

(development
 (depends-on "ert-runner"))

